###

POST https://sandbox.api.payulatam.com/reports-api/4.0/service.cgi
Host: sandbox.api.payulatam.com
Content-Type: application/json; charset=utf-8
Accept: application/json

{
   "test": false,
   "language": "en",
   "command": "PING",
   "merchant": {
      "apiLogin": "pRRXKOl8ikMmt9u",
      "apiKey": "4Vj8eK4rloUd272L48hsrarnUA"
   }
}

###
POST https://sandbox.api.payulatam.com/payments-api/4.0/service.cgi
Host: sandbox.api.payulatam.com
Content-Type: application/json; charset=utf-8
Accept: application/json

{
   "test": false,
   "language": "en",
   "command": "GET_PAYMENT_METHODS",
   "merchant": {
      "apiLogin": "pRRXKOl8ikMmt9u",
      "apiKey": "4Vj8eK4rloUd272L48hsrarnUA"
   }
}



###
POST https://sandbox.api.payulatam.com/payments-api/4.0/service.cgi
Host: sandbox.api.payulatam.com
Content-Type: application/json; charset=utf-8
Accept: application/json

{
   "language": "es",
   "command": "SUBMIT_TRANSACTION",
   "merchant": {
      "apiKey": "4Vj8eK4rloUd272L48hsrarnUA",
      "apiLogin": "pRRXKOl8ikMmt9u"
   },
   "transaction": {
      "order": {
         "accountId": "512321",
         "referenceCode": "TestPayU",
         "description": "payment test",
         "language": "es",
         "signature": "7ee7cf808ce6a39b17481c54f2c57acc",
         "additionalValues": {
            "TX_VALUE": {
               "value": 20000,
               "currency": "COP"
         },
            "TX_TAX": {
               "value": 3193,
               "currency": "COP"
         },
            "TX_TAX_RETURN_BASE": {
               "value": 16806,
               "currency": "COP"
         }
         },
         "buyer": {
            "fullName": "First name and second buyer  name",
            "emailAddress": "buyer_test@test.com",
            "contactPhone": "7563126",
            "dniNumber": "5415668464654",
            "shippingAddress": {
               "street1": "calle 100",
               "street2": "5555487",
               "city": "Bogota",
               "state": "Cundinamarca",
               "country": "CO",
               "postalCode": "000000",
               "phone": "7563126"
            }
         }
      },
      "payer": {
         "fullName": "First name and second payer name",
         "emailAddress": "payer_test@test.com",
         "contactPhone": "7563126",
         "dniNumber": "5415668464654",
         "billingAddress": {
            "street1": "calle 93",
            "street2": "125544",
            "city": "Bogota",
            "state": "Bogota DC",
            "country": "CO",
            "postalCode": "000000",
            "phone": "7563126"
         }
      },
      "creditCard": {
         "number": "4097440000000004",
         "securityCode": "321",
         "expirationDate": "2019/12",
         "name": "REJECTED"
      },
      "extraParameters": {
         "INSTALLMENTS_NUMBER": 1
      },
      "type": "AUTHORIZATION_AND_CAPTURE",
      "paymentMethod": "VISA",
      "paymentCountry": "CO",
      "deviceSessionId": "vghs6tvkcle931686k1900o6e1",
      "ipAddress": "127.0.0.1",
      "cookie": "pt1t38347bs6jc9ruv2ecpv7o2",
      "userAgent": "Mozilla/5.0 (Windows NT 5.1; rv:18.0) Gecko/20100101 Firefox/18.0"
   },
   "test": false
}

###
POST https://sandbox.api.payulatam.com/payments-api/4.0/service.cgi
Host: sandbox.api.payulatam.com
Content-Type: application/json; charset=utf-8
Accept: application/json

{
   "language": "es",
   "command": "SUBMIT_TRANSACTION",
   "merchant": {
      "apiKey": "4Vj8eK4rloUd272L48hsrarnUA",
      "apiLogin": "pRRXKOl8ikMmt9u"
   },
   "transaction": {
      "order": {
         "accountId": "512321",
         "referenceCode": "TestPayU",
         "description": "payment test",
         "language": "es",
         "signature": "7ee7cf808ce6a39b17481c54f2c57acc",
         "additionalValues": {
            "TX_VALUE": {
               "value": 20000,
               "currency": "COP"
         },
            "TX_TAX": {
               "value": 3193,
               "currency": "COP"
         },
            "TX_TAX_RETURN_BASE": {
               "value": 16806,
               "currency": "COP"
         }
         },
         "buyer": {
            "fullName": "Hermelindo Perez",
            "emailAddress": "buyer_test@test.com"
         }
      },
      "type": "AUTHORIZATION_AND_CAPTURE",
      "paymentMethod": "EFECTY",
      "expirationDate": "2019-03-02T00:00:00",
      "paymentCountry": "CO",
      "ipAddress": "127.0.0.1"
   },
   "test": false
}

###

POST https://sandbox.api.payulatam.com/reports-api/4.0/service.cgi
Host: sandbox.api.payulatam.com
Content-Type: application/json; charset=utf-8
Accept: application/json

{
   "test": false,
   "language": "en",
   "command": "ORDER_DETAIL",
   "merchant": {
      "apiLogin": "pRRXKOl8ikMmt9u",
      "apiKey": "4Vj8eK4rloUd272L48hsrarnUA"
   },
   "details": {
      "orderId": 845343230
   }
}


###
POST https://sandbox.api.payulatam.com/reports-api/4.0/service.cgi
Host: sandbox.api.payulatam.com
Content-Type: application/json; charset=utf-8
Accept: application/json

{
   "test": false,
   "language": "en",
   "command": "TRANSACTION_RESPONSE_DETAIL",
   "merchant": {
      "apiLogin": "pRRXKOl8ikMmt9u",
      "apiKey": "4Vj8eK4rloUd272L48hsrarnUA"
   },
   "details": {
      "transactionId": "d566556d-2ce3-4d41-87e2-07e79e0405c1"
   }
}